// This file is auto-generated by scripts/generate-daily-schedule.mjs
export const dailyScheduleMeta = {
  "generatedAt": "2026-03-14T07:45:01.450Z",
  "startDate": "2026-03-14",
  "days": 90
};

export const dailySchedule = [
  {
    "date": "2026-03-14",
    "category": "OFFICE SUPPLIES",
    "word": "ERASER",
    "mapId": "king"
  },
  {
    "date": "2026-03-15",
    "category": "UNDER THE SEA",
    "word": "MOLLUSK",
    "mapId": "bell"
  },
  {
    "date": "2026-03-16",
    "category": "GROCERY LIST",
    "word": "ALMONDS",
    "mapId": "alien"
  },
  {
    "date": "2026-03-17",
    "category": "OCCUPATION",
    "word": "FLIGHT ATTENDANT",
    "mapId": "llama"
  },
  {
    "date": "2026-03-18",
    "category": "PHRASE",
    "word": "BY ALL MEANS",
    "mapId": "classic"
  },
  {
    "date": "2026-03-19",
    "category": "AROUND TOWN",
    "word": "LAUNDROMAT",
    "mapId": "its-a-plane"
  },
  {
    "date": "2026-03-20",
    "category": "ART & ENTERTAINMENT",
    "word": "GLASSBLOWING",
    "mapId": "bell"
  },
  {
    "date": "2026-03-21",
    "category": "WEATHER",
    "word": "RAINFALL",
    "mapId": "pretzel"
  },
  {
    "date": "2026-03-22",
    "category": "BRAND",
    "word": "GOOGLE",
    "mapId": "alien"
  },
  {
    "date": "2026-03-23",
    "category": "MOVIE",
    "word": "GHOSTBUSTERS",
    "mapId": "king"
  },
  {
    "date": "2026-03-24",
    "category": "MUSICAL ARTIST",
    "word": "HARRY STYLES",
    "mapId": "pretzel"
  },
  {
    "date": "2026-03-25",
    "category": "MOVIE",
    "word": "SCARFACE",
    "mapId": "froggy"
  },
  {
    "date": "2026-03-26",
    "category": "CLOTHING",
    "word": "FLEECE JACKET",
    "mapId": "king"
  },
  {
    "date": "2026-03-27",
    "category": "GAME",
    "word": "DONKEY KONG",
    "mapId": "llama"
  },
  {
    "date": "2026-03-28",
    "category": "BRAND",
    "word": "AIRBNB",
    "mapId": "bell"
  },
  {
    "date": "2026-03-29",
    "category": "UNDER THE SEA",
    "word": "SHRIMP",
    "mapId": "alien"
  },
  {
    "date": "2026-03-30",
    "category": "PHRASE",
    "word": "KEEP IT REAL",
    "mapId": "pisces"
  },
  {
    "date": "2026-03-31",
    "category": "OFFICE SUPPLIES",
    "word": "HOLE PUNCH",
    "mapId": "llama"
  },
  {
    "date": "2026-04-01",
    "category": "THE COSMOS",
    "word": "JUPITER",
    "mapId": "octopus"
  },
  {
    "date": "2026-04-02",
    "category": "GAME",
    "word": "SOLITAIRE",
    "mapId": "bell"
  },
  {
    "date": "2026-04-03",
    "category": "FAMOUS PLACE",
    "word": "ISTANBUL",
    "mapId": "its-a-bird"
  },
  {
    "date": "2026-04-04",
    "category": "BRAND",
    "word": "SAMSUNG",
    "mapId": "froggy"
  },
  {
    "date": "2026-04-05",
    "category": "COUNTRY",
    "word": "BELIZE",
    "mapId": "alien"
  },
  {
    "date": "2026-04-06",
    "category": "AROUND THE HOUSE",
    "word": "THERMOSTAT",
    "mapId": "leo"
  },
  {
    "date": "2026-04-07",
    "category": "ART & ENTERTAINMENT",
    "word": "BROADWAY",
    "mapId": "its-a-bird"
  },
  {
    "date": "2026-04-08",
    "category": "PHRASE",
    "word": "ON THE SPOT",
    "mapId": "queen"
  },
  {
    "date": "2026-04-09",
    "category": "GAME",
    "word": "CANDY CRUSH",
    "mapId": "new-map-1"
  },
  {
    "date": "2026-04-10",
    "category": "GROCERY LIST",
    "word": "ALUMINUM FOIL",
    "mapId": "its-a-plane"
  },
  {
    "date": "2026-04-11",
    "category": "AROUND THE HOUSE",
    "word": "POSTER",
    "mapId": "pisces"
  },
  {
    "date": "2026-04-12",
    "category": "VEHICLE",
    "word": "CARGO SHIP",
    "mapId": "alien"
  },
  {
    "date": "2026-04-13",
    "category": "ANIMAL",
    "word": "GOLDFISH",
    "mapId": "bell"
  },
  {
    "date": "2026-04-14",
    "category": "VEHICLE",
    "word": "FORKLIFT",
    "mapId": "pretzel"
  },
  {
    "date": "2026-04-15",
    "category": "PHRASE",
    "word": "IN YOUR DREAMS",
    "mapId": "llama"
  },
  {
    "date": "2026-04-16",
    "category": "OCCUPATION",
    "word": "FIREFIGHTER",
    "mapId": "alien"
  },
  {
    "date": "2026-04-17",
    "category": "MUSICAL ARTIST",
    "word": "PRINCE",
    "mapId": "its-a-plane"
  },
  {
    "date": "2026-04-18",
    "category": "WORLD OF SPORTS",
    "word": "PGA TOUR",
    "mapId": "octopus"
  },
  {
    "date": "2026-04-19",
    "category": "MUSICAL ARTIST",
    "word": "THE BEATLES",
    "mapId": "classic"
  },
  {
    "date": "2026-04-20",
    "category": "HISTORICAL FIGURE",
    "word": "THOMAS JEFFERSON",
    "mapId": "its-a-plane"
  },
  {
    "date": "2026-04-21",
    "category": "ART & ENTERTAINMENT",
    "word": "ANIMATION",
    "mapId": "bell"
  },
  {
    "date": "2026-04-22",
    "category": "AROUND THE HOUSE",
    "word": "BATHMAT",
    "mapId": "pisces"
  },
  {
    "date": "2026-04-23",
    "category": "COUNTRY",
    "word": "AFGHANISTAN",
    "mapId": "llama"
  },
  {
    "date": "2026-04-24",
    "category": "THE COSMOS",
    "word": "NORTH STAR",
    "mapId": "classic"
  },
  {
    "date": "2026-04-25",
    "category": "MOVIE",
    "word": "CITIZEN KANE",
    "mapId": "octopus"
  },
  {
    "date": "2026-04-26",
    "category": "VEHICLE",
    "word": "SPEEDBOAT",
    "mapId": "alien"
  },
  {
    "date": "2026-04-27",
    "category": "UNDER THE SEA",
    "word": "MANATEE",
    "mapId": "queen"
  },
  {
    "date": "2026-04-28",
    "category": "GROCERY LIST",
    "word": "CHICKEN BROTH",
    "mapId": "classic"
  },
  {
    "date": "2026-04-29",
    "category": "THE COSMOS",
    "word": "GALAXY",
    "mapId": "alien"
  },
  {
    "date": "2026-04-30",
    "category": "ART & ENTERTAINMENT",
    "word": "STAGE PLAY",
    "mapId": "froggy"
  },
  {
    "date": "2026-05-01",
    "category": "THE COSMOS",
    "word": "NEPTUNE",
    "mapId": "queen"
  },
  {
    "date": "2026-05-02",
    "category": "MOVIE",
    "word": "FROZEN",
    "mapId": "its-a-bird"
  },
  {
    "date": "2026-05-03",
    "category": "ANIMAL",
    "word": "CHEETAH",
    "mapId": "alien"
  },
  {
    "date": "2026-05-04",
    "category": "COUNTRY",
    "word": "AUSTRALIA",
    "mapId": "llama"
  },
  {
    "date": "2026-05-05",
    "category": "THE COSMOS",
    "word": "BLACK HOLE",
    "mapId": "classic"
  },
  {
    "date": "2026-05-06",
    "category": "OFFICE SUPPLIES",
    "word": "MAIL TRAY",
    "mapId": "bell"
  },
  {
    "date": "2026-05-07",
    "category": "FAMOUS PLACE",
    "word": "SILICON VALLEY",
    "mapId": "classic"
  },
  {
    "date": "2026-05-08",
    "category": "AROUND TOWN",
    "word": "MAIN STREET",
    "mapId": "its-a-bird"
  },
  {
    "date": "2026-05-09",
    "category": "BRAND",
    "word": "VERIZON",
    "mapId": "pisces"
  },
  {
    "date": "2026-05-10",
    "category": "UNDER THE SEA",
    "word": "HALIBUT",
    "mapId": "its-a-bird"
  },
  {
    "date": "2026-05-11",
    "category": "AROUND TOWN",
    "word": "HARDWARE STORE",
    "mapId": "pretzel"
  },
  {
    "date": "2026-05-12",
    "category": "GROCERY LIST",
    "word": "APPLE JUICE",
    "mapId": "leo"
  },
  {
    "date": "2026-05-13",
    "category": "VEHICLE",
    "word": "CRUISE SHIP",
    "mapId": "froggy"
  },
  {
    "date": "2026-05-14",
    "category": "FAMOUS PLACE",
    "word": "GOLDEN GATE BRIDGE",
    "mapId": "new-map-1"
  },
  {
    "date": "2026-05-15",
    "category": "COUNTRY",
    "word": "TURKEY",
    "mapId": "queen"
  },
  {
    "date": "2026-05-16",
    "category": "OFFICE SUPPLIES",
    "word": "FAX MACHINE",
    "mapId": "its-a-plane"
  },
  {
    "date": "2026-05-17",
    "category": "UNDER THE SEA",
    "word": "ANGLERFISH",
    "mapId": "alien"
  },
  {
    "date": "2026-05-18",
    "category": "BRAND",
    "word": "TOSHIBA",
    "mapId": "bell"
  },
  {
    "date": "2026-05-19",
    "category": "WEATHER",
    "word": "MONSOON",
    "mapId": "pisces"
  },
  {
    "date": "2026-05-20",
    "category": "MUSICAL ARTIST",
    "word": "RADIOHEAD",
    "mapId": "classic"
  },
  {
    "date": "2026-05-21",
    "category": "HISTORICAL FIGURE",
    "word": "ALEXANDER THE GREAT",
    "mapId": "pretzel"
  },
  {
    "date": "2026-05-22",
    "category": "MOVIE",
    "word": "HALLOWEEN",
    "mapId": "new-map-1"
  },
  {
    "date": "2026-05-23",
    "category": "PHRASE",
    "word": "TIME WILL TELL",
    "mapId": "its-a-plane"
  },
  {
    "date": "2026-05-24",
    "category": "ANIMAL",
    "word": "ELEPHANT",
    "mapId": "leo"
  },
  {
    "date": "2026-05-25",
    "category": "FAMOUS PLACE",
    "word": "GREAT BARRIER REEF",
    "mapId": "alien"
  },
  {
    "date": "2026-05-26",
    "category": "VEHICLE",
    "word": "SCHOOL BUS",
    "mapId": "queen"
  },
  {
    "date": "2026-05-27",
    "category": "COUNTRY",
    "word": "INDONESIA",
    "mapId": "pisces"
  },
  {
    "date": "2026-05-28",
    "category": "MOVIE",
    "word": "DUNKIRK",
    "mapId": "leo"
  },
  {
    "date": "2026-05-29",
    "category": "COUNTRY",
    "word": "NETHERLANDS",
    "mapId": "new-map-1"
  },
  {
    "date": "2026-05-30",
    "category": "PHRASE",
    "word": "UP TO YOU",
    "mapId": "leo"
  },
  {
    "date": "2026-05-31",
    "category": "FOOD AND DRINK",
    "word": "CROISSANT",
    "mapId": "its-a-bird"
  },
  {
    "date": "2026-06-01",
    "category": "ANIMAL",
    "word": "ANACONDA",
    "mapId": "leo"
  },
  {
    "date": "2026-06-02",
    "category": "AROUND TOWN",
    "word": "POLICE STATION",
    "mapId": "classic"
  },
  {
    "date": "2026-06-03",
    "category": "WEATHER",
    "word": "BLIZZARD",
    "mapId": "froggy"
  },
  {
    "date": "2026-06-04",
    "category": "THE COSMOS",
    "word": "DARK MATTER",
    "mapId": "llama"
  },
  {
    "date": "2026-06-05",
    "category": "GROCERY LIST",
    "word": "CANNED BEANS",
    "mapId": "pisces"
  },
  {
    "date": "2026-06-06",
    "category": "WEATHER",
    "word": "THUNDER",
    "mapId": "its-a-plane"
  },
  {
    "date": "2026-06-07",
    "category": "WORLD OF SPORTS",
    "word": "HALF COURT",
    "mapId": "bell"
  },
  {
    "date": "2026-06-08",
    "category": "BRAND",
    "word": "ROLLS ROYCE",
    "mapId": "llama"
  },
  {
    "date": "2026-06-09",
    "category": "OFFICE SUPPLIES",
    "word": "GLUE STICK",
    "mapId": "alien"
  },
  {
    "date": "2026-06-10",
    "category": "FAMOUS PLACE",
    "word": "LAS VEGAS STRIP",
    "mapId": "pretzel"
  },
  {
    "date": "2026-06-11",
    "category": "CLOTHING",
    "word": "TENNIS SHOES",
    "mapId": "froggy"
  }
];
